version: '3'
services:
  clients-api:
    build: ./clients-api
    ports:
      - "3010:3000"
    networks:
      - app-network

  playlists-api:
    build: ./playlists-api
    ports:
      - "3001:3000"
    networks:
      - app-network

  soirees-api:
    build: ./soirees-api
    ports:
      - "3020:3000"
    networks:
      - app-network

  playchange-front:
    build: ./playchange-front
    ports:
      - "3030:3000"
    networks:
      - app-network

  reservation-front:
    build: ./reservation-front
    ports:  
      - "3040:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
