name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: pull and deply on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.155.231.97
          username: maalsi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/cesi-test-cicd
            git clone https://github.com/SamPotentier/cloud-natif.git
            docker compose down
            docker compose up -d --build
